### ISSUE TITLE
Hello, could you explain the structure of the data set

### ISSUE THREAD

**Issue by JCJCut** [taveraantonio/AIAS#1]
The structure of agriculture-vision-2021 is completely different from that mentioned in the code, which makes it impossible to run the code. What is the relationship between the dataset structure of the project and the original dataset? Thank you very much!

**Comment by VoDangChau** [comment]
Hello sir, I'm trying to reproduce the result for my project, but so far I can not find the suitable config file in the file "configs" to run test.py as it show the error "ConfigDict object has no attribute ...". Can you help me out, please ?
